server:
  port: 5050


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
 application:
    name: gateway-server
 cloud:
    gateway:
     routes:
     - id: couponModule
       predicates: 
       - Path=/coupons/**
       uri: lb://COUPON-SERVICE
     - id: productModule
       predicates: 
       - Path=/products/**
       uri: lb://PRODUCT-SERVICE 
     - id: couponAppModule
       predicates: 
       - Path=/coupon-api/**
       uri: lb://COUPON-SERVICE-APP
     - id: productAppModule
       predicates: 
       - Path=/product-api/**
       uri: lb://PRODUCT-SERVICE-APP
       
 zipkin: 
  base-url: http://localhost:9411/
  
