#spring.datasource.url=jdbc://localhost:6060/javabatch

#spring.datasource.username=root 

#spring.datasource.password=Temp1234
#spring.jpa.hibernate.ddl-auto=create
server:
  port: 6060
spring:
 datasource:
  url: jdbc:mysql://localhost:6060/javabatch
  username: root
  password: Temp1234
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
  properties:
   hibernate:
   formate_sql: true
  # database-platform: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
      base-path: /myactuator
        
  endpoint:
    shutdown:
      enabled: true
      
      
      
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
      
info:
   createdBy: shiva siddu
   modified : 22june22
   
   
logging:
  level:
    com:
     zensar: debug
  
 
  
  
 
   